# This is a custom Travis configuration that tests against multiple versions
# of eprover and Isabelle. It is based on the simple stack configuration, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/

# Use new container infrastructure to enable caching
sudo: false

dist: bionic

language: generic

cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/.eprover"
  - "$HOME/.isabelle"
  - "$HOME/isabelle"

addons:
  apt:
    packages:
    - libgmp-dev # needed by GHC
    # Isabelle:
    - curl
    - mercurial
    - p7zip-full
    - texlive-fonts-extra
    - texlive-font-utils
    - texlive-latex-extra
    - texlive-science
    - less
    - libfontconfig1
    - libgomp1
    - libwww-perl
    - rlwrap
    - unzip

os:
- linux
- osx
env:
- EVER=2.3
- EVER=2.2
- EVER=2.1
- EVER=2.0

before_install:
# Download and unpack the stack and eprover executables
- mkdir -p ~/.local/bin
- mkdir -p ~/.eprover
- export PATH=$HOME/.local/bin:$HOME/.eprover:$PATH
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
- |
  if [ ! -f ~/.eprover/eprover ]; then
    travis_retry curl -L http://wwwlehre.dhbw-stuttgart.de/~sschulz/WORK/E_DOWNLOAD/V_$EVER/E.tgz | tar xz
    cd E
    ./configure --bindir=$HOME/.eprover
    make
    make install
    cd ..
  fi

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests
- stack --no-terminal test

before_deploy:
- export GITHUB_USER=anfelor
- export RELEASE=ad2d84c42380 # hg commit of isabelle to build
# Abort on all but one worker:
- | 
  if [ "$EENV" != "2.3" ] || [ `uname` != "Darwin" ]
  then
    travis_terminate 0
  fi
# Build isabelle
- cd ~
- |
  if [ ! -d "isabelle" ]
  then
    hg clone https://isabelle.in.tum.de/repos/isabelle
    mkdir -p .isabelle/etc
    touch .isabelle/etc/settings
    echo "init_component \"~/Naproche-SAD\"" > .isabelle/etc/settings
    cd isabelle
    ./bin/isabelle components -I
  else
    cd isabelle
    hg pull -u
  fi
- ./bin/isabelle components -a
- ./bin/isabelle build -o system_heaps -b HOL
# Build the project
- cd ../$GITHUB_USER/Naproche-SAD
- ../../.bin/isabelle build -e -d Isabelle Naproche-Build
- stack build
- cd ../..
# Bundle
- tar -zcvf naproche.tar.gz $GITHUB_USER/Naproche-SAD
- isabelle/Admin/build_release -r ad2d84c42380 -c naproche.tar.gz -b Pure -R Isabelle_Naproche .

deploy:
  provider: releases
  api_key:
    secure: vwvsiVTLG4SV8ncVUqHANkD/6/Dh4d7PD1AT+fTTPgJoqfy/0KwH2MYLh4u3vjOtEyepDmis0HJDpd/cVNy8eEkppSiu+NTuUpNxJkImtAfONxJnvQYhEn6pmxeaMw/t3VYYCrC3v1ojLXKieH2fTUSQs8FAHqkbXhEpHOX/bzuzf5p4VBeQNn6qY+b9vYttOIuoPS5CbzRmQJ5OjDkN4BaPGJbLXRx1GcbWOL18G0szqlBk9Pmv1Z7Yzs4Q4Wgm5Y9D9Op5SJTahKYGSnR8dzRrtqtW+0qNWfURaFkvbSnst+XdCo1qXeEo1e1KuPcrUIu32LMpG6RcHfS03FdHkebCYeBGf2MeMWl0hTqTPRbC1/yLfbiP2rqP6oYYBj4nTUfmxDnwmBX7cwS0ZT5dvFQYd4tep0Ma1sIw7OBArJI+/jjj+GUBt1fmbjyhHEO0HxHIA5mE+KdYrK5Oohqm2PQDBGfBrZoPmKcliV1AXokN3ycMN8Trh/au/6IfolKVLFNmUPRE4AIirS3laPNt/jP6+m5T9n/H9+86Ga1y/uAk727qFnjykWVDYuLEogdO2XLdOFoY6A5af4du5dWAqNbNLMDJhWB9cMXMpiRjOSp/z4vl0lleKhZhGN8GPNElM0nBwfj30/Itqgz3UKoCJeY1W6LoZzU0uIZVC6vjFOw=
  file: dist-Isabelle_Naproche/Isabelle_Naproche.tar.gz
  on:
    repo: anfelor/Naproche-SAD
  draft: true
