# This is a custom Travis configuration that tests against multiple versions
# of eprover and Isabelle. It is based on the simple stack configuration, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/

# Use new container infrastructure to enable caching
sudo: false

# Choose a build environment
dist: xenial

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.eprover

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
matrix:
  include:
  - env: EVER=2.3
    compiler: ": eprover 2.3"
  - env: EVER=2.2
    compiler: ": eprover 2.2"
  - env: EVER=2.1
    compiler: ": eprover 2.1"
  - env: EVER=2.0
    compiler: ": eprover 2.0"

  - env: EVER=2.3
    compiler: ": eprover 2.3"
    os: osx
  - env: EVER=2.2
    compiler: ": eprover 2.2"
    os: osx
  - env: EVER=2.1
    compiler: ": eprover 2.1"
    os: osx
  - env: EVER=2.0
    compiler: ": eprover 2.0"
    os: osx

before_install:
# Download and unpack the stack and eprover executables
- mkdir -p ~/.local/bin
- mkdir -p ~/.eprover
- export PATH=$HOME/.local/bin:$HOME/.eprover:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- |
  if [[ ! -f "~/.eprover/eprover" ]]; then
  travis_retry curl -L http://wwwlehre.dhbw-stuttgart.de/~sschulz/WORK/E_DOWNLOAD/V_$EVER/E.tgz | tar xz
  cd E
  ./configure --bindir=$HOME/.eprover
  make
  make install
  cd ..
  fi

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests
- stack --no-terminal test --haddock --no-haddock-deps