name:                Naproche-SAD
version:             0.1.0.0
github:              "Naproche/Naproche-SAD"
license:             GPL-3

extra-source-files:
- README.md

description:         <https://github.com/Naproche/Naproche-SAD>

ghc-options:
  - -O2
  - -Wall
  - -fno-warn-unused-do-bind
  - -fno-warn-unused-matches
  - -fno-warn-name-shadowing
  
default-extensions:
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - PartialTypeSignatures
  - ScopedTypeVariables

library:
  source-dirs:
    - src
  exposed-modules:
    - SAD.API
    - SAD.Main
  when:
    - condition: true
      dependencies:
        - pide-hs
  dependencies:
    - base >= 4.7 && < 5
    - containers
    - process
    - ghc-prim
    - hashable
    - time
    - mtl
    - transformers
    - bytestring
    - text
    - yaml

executables:
  Naproche-SAD:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Naproche-SAD
    - base >= 4.7 && < 5

tests:
  Naproche-SAD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Naproche-SAD
    - base >= 4.7 && < 5
    - containers
    - process
    - text