name:                pide-hs
version:             0.1.0.0
github:              "Naproche/Naproche-SAD"
license:             GPL-3

description:         <https://github.com/Naproche/Naproche-SAD>

ghc-options:
  - -O2
  - -Wall
  - -fno-warn-unused-do-bind
  - -fno-warn-unused-matches
  - -fno-warn-name-shadowing

library:
  source-dirs:
    - src
  exposed-modules:
    - PIDE
    - PIDE.SourcePos
  dependencies:
    - base >= 4.7 && < 5
    - containers
    - process
    - ghc-prim
    - time
    - text
    - bytestring
    - utf8-string
    - network
    - split
    - uuid
    - threads
  default-extensions:
    - ScopedTypeVariables